# Generated by Django 5.0.6 on 2024-05-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/img'),
        ),
    ]
