# Generated by Django 5.0.6 on 2024-05-19 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0004_contact_alter_usuario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El formato del RUT debe ser válido.', regex='^\\d{7,8}-[\\dKk]$')]),
        ),
    ]
